//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetBiblio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRE
    {
        public int ID_LIVRE { get; set; }
        public string ISBN { get; set; }
        public string TITRE { get; set; }
        public Nullable<System.DateTime> ANNEE_EDITION { get; set; }
        public string FICHIER { get; set; }
        public Nullable<System.DateTime> DATE_SAISIE { get; set; }
        public Nullable<int> ID_AUTEUR { get; set; }
        public Nullable<int> ID_GENRE { get; set; }
        public Nullable<int> ID_EDITEUR { get; set; }
    
        public virtual AUTEUR AUTEUR { get; set; }
        public virtual EDITEUR EDITEUR { get; set; }
        public virtual GENRE GENRE { get; set; }
    }
}
